services:
  http-server:
    build:
      context: ../..
      dockerfile: packages/lab1/Dockerfile
    develop:
      # Create a `watch` configuration to update the app
      watch:
        - action: sync
          path: .
          target: /workspace
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml
    network_mode: host
    volumes:
      - ./www:/workspace/packages/lab1/www
    command: ["uv", "run", "./packages/lab1/src/lab1/server.py", "/workspace/packages/lab1/www", "8080"]
    
  http-client:
    build:
      context: ../..
      dockerfile: packages/lab1/Dockerfile
    network_mode: host
    profiles:
      - client
    volumes:
      - ${DOWNLOAD_DIR:-./downloads}:/workspace/downloads
    command: ["uv", "run", "./packages/lab1/src/lab1/client.py", "${SERVER_HOST:-localhost}", "${SERVER_PORT:-8080}", "${URL_PATH:-index.html}", "/workspace/downloads"]
    environment:
      - DOWNLOAD_DIR=${DOWNLOAD_DIR:-/workspace/downloads}
    depends_on:
      - http-server
